% creates base directory name for particular model and properties

function dir_base = create_dir_base(model,properties)

if strcmp(model,'FFNN')
    dir_base = ['FFNN/c' num2str(properties{1}) ...
        '_' properties{2} properties{3} '/train' num2str(100*properties{4}) ...
        '_val' num2str(100*properties{5}) '_test' num2str(100*properties{6})];
elseif strcmp(model,'RFR')
    dir_base = ['RFR/c' num2str(properties{1}) ...
        '_' properties{2} properties{3} '/tr' ...
        num2str(properties{4}) '_lf' num2str(properties{5})];
elseif strcmp(model,'GBM')
    dir_base = ['GBM/c' num2str(properties{1}) '_' properties{2} ...
        properties{3} '/tr' num2str(properties{4}) '_bn' num2str(properties{5})];
end
