% run_osse
%
% DESCRIPTION:
% This function use the combined dataset to subsample models,
% train test machine learning algorithms, and apply those
% algorithms to model grids to test their performance.
%
% AUTHOR: J. Sharp, UW CICOES / NOAA PMEL
%
% DATE: 12/5/2025

function run_osse(fpaths,model_types,model_folders,realizations,...
    grid_labels,grid_types,param_props,file_date,snap_date,...
    float_file_ext,start_year,end_year,num_clusters,variables,...
    clust_vars,train_ratio,val_ratio,test_ratio,thresh,...
    data_per_osse,numWorkers_train,numWorkers_predict,flt,gld,ctd)

%% define dataset extensions
if flt == 1; float_ext = 'f'; else float_ext = ''; end
if gld == 1; glodap_ext = 'g'; else glodap_ext = ''; end
if ctd == 1; ctd_ext = 'w'; else ctd_ext = ''; end

%% load data
load([param_props.dir_name '/Data/wod_data_' num2str(start_year) ...
    '_' num2str(end_year)],'all_data');

%% loop through each model
for m = 1:length(model_types)

    %% process models
    process_cmip_model(model_types{m},[fpaths.model_path model_folders{m} '/'],...
        snap_date,start_year,realizations{m},grid_labels{m},grid_types{m});

    %% subsample models
    subsample_cmip_model(param_props,all_data,model_types{m},...
        [fpaths.model_path model_folders{m} '/'],file_date,...
        snap_date,float_file_ext,start_year,realizations{m},...
        float_ext,glodap_ext,ctd_ext);

    %% form clusters
    gmm_clustering(param_props,fpaths,model_types{m},...
        start_year,end_year,snap_date,float_file_ext,clust_vars,num_clusters,...
        numWorkers_predict,flt,gld,ctd,'rlz',realizations{m});

    %% cluster data
    assign_data_to_clusters(param_props,model_types{m},snap_date,...
        float_file_ext,clust_vars,num_clusters,flt,gld,ctd);
    plot_data_by_cluster(param_props,model_types{m},file_date,...
        float_file_ext,num_clusters,numWorkers_train,flt,gld,ctd);
    % plot_data_over_clusters(param,model_types{m},file_date,float_file_ext,num_clusters,numWorkers_train);

    %% train algorithms
    % train feed forward neural networks
    train_gobai('FFNN',param_props,model_types{m},file_date,float_file_ext,...
        num_clusters,variables,thresh,numWorkers_train,snap_date,...
        flt,gld,ctd,'reduce_data',data_per_osse,'train_ratio',...
        train_ratio,'val_ratio',val_ratio,'test_ratio',test_ratio);

    %% predict on grid
    % predict on grid using feed forward neural networks
    predict_gobai('FFNN',param_props,fpaths,...
        model_types{m},file_date,float_file_ext,num_clusters,...
        variables,thresh,numWorkers_predict,clust_vars,start_year,end_year,...
        snap_date,flt,gld,ctd,'train_ratio',train_ratio,'val_ratio',val_ratio,...
        'test_ratio',test_ratio,'rlz',realizations{m});

    %% average grids across all algorithms
    % combine_gobai(param_props,[fpaths.model_path model_folders{m} '/'],...
    %     [fpaths.model_path model_folders{m} '/'],...
    %     model_types{m},file_date,float_file_ext,...
    %     num_clusters_1,num_clusters_2,num_clusters_3,start_year,end_year,snap_date,train_ratio,...
    %     val_ratio,test_ratio,numtrees,minLeafSize,...
    %     numstumps,numbins,'rlz',realizations{m});

    %% compare reconstructed model grid to original
    compare_osse(param_props,fpaths,...
        model_types{m},file_date,float_file_ext,...
        num_clusters,start_year,snap_date,train_ratio,...
        val_ratio,test_ratio,realizations{m},...
        float_ext,glodap_ext,ctd_ext);

end

%% compare all osse experiments
compare_all_osses(param_props,fpaths,model_types,realizations,...
    num_clusters,file_date,float_file_ext,train_ratio,val_ratio,...
    test_ratio,float_ext,glodap_ext,ctd_ext);
